### PR TITLE
CE06ISSM deployment 6 (Endurance 7)

### PR DESCRIPTION
**Pull request by desiderr**

### CODE REVIEW

**Comment by danmergens** [comment]
Need to resolve your conflicts - probably need to view the differences offline and determine the correction (maybe there was a different line ending which is causing everything to look different?)

**Comment by desiderr** [comment]
Dan - I completely re-ordered the columns of the 3 deploy.csv files, and I re-ordered the rows of the last deployment in each; Pete had said that the working of these files was not sensitive to row or column order, except that in order to comment out a row the first column needs to be CUIDdeploy.

Maybe I need to regress to the original order of the 3 files to resolve the conflicts, have the PR merged, and then try to re-order just one file without changing any other files to see if that will fly.

- Russ


----- Original Message -----

**Comment by danmergens** [comment]
Sounds like the best approach - reordering is fine, but we want to do it in steps - content changes, then format changes. Thanks

**Comment by najascutellatus** [comment]
The problem is that Lori changed some start/end times in an earlier Pull request (#188). I don't think your repository was up to date with the master repository.

**Comment by desiderr** [comment]
What do I need to do?

----- Original Message -----

**Comment by najascutellatus** [comment]
I meant to send a pull request back to desiderr-master but it sent it to ooi-integration instead.

Rus, I fixed the merge issue in #193. It was due to a combination of missing Lori's time edits and re-arranging the columns. There are two issues that will affect the system: 

1. CGINS-PCO2WB-C0019, which is listed in CE06ISSM_Deploy.csv does not exist in sensor bulk. Please add this.

2. Lines 125-153 in CE06ISSM_Deploy.csv are listed as deployment 6, however, they have start dates that are the same as the previous lines (deployment 5.) Please fix this as well.

I suggest deleting your current fork and re-forking from ooi-integration and then committing the changes in a new PR

Closing this PR

**Pull request closed without merging**
