### PR TITLE
Added cc_scale_factor (1,2,3,4) to all ADCPTG cal sheets

### PR DESCRIPTION
**Pull request by rtravis-whoi**
Added cc_scale_factor (1,2,3,4) to all ADCPTG cal sheets

### CODE REVIEW

**Comment by leilabbb** [comment]
Dan,
 Are you saying we should revert to adding back the CC_depth to the ADCP cal sheets because it is used by the stream engine?

**Comment by rtravis-whoi** [comment]
I thought with this new cal sheet set-up that depth and lat/lon are all pulled from the deployment sheets?

**Comment by desiderr** [comment]
I've been meaning to check out whether or not the CC_depth parameter is being used to process Endurance ADCP data, and given the current discussion now seems like a good time.

My understanding is that the Endurance ADCPs should be using the pd0 parsing, which includes the ADCP's pressure sensor measurement. Therefore, these instruments do not require, and the processing of their data should not be using, the CC_depth parameter. (The pd8 parsing, on the other hand, does not include pressure.)

- Russ

----- Original Message -----

**Comment by danmergens** [comment]
Somehow I forgot that I just updated stream engine
<https://uframe-cm.ooi.rutgers.edu/issues/9306> to use the asset management
value when CC_depth is specified in the stream definition.

**Comment by leilabbb** [comment]
Ok, so the changes are acceptable .... merging Rebecca commit

**Pull request merged**
