### PR TITLE
Metadata review part 1

### PR DESCRIPTION
**Pull request by cdobs**
These proposed changes are the first round of updates to come from our metadata review process. The instruments reviewed include CTDGVM, PCO2WB, PCO2WC, PHSEND, PHSENE, PHSENF.

### CODE REVIEW

**Comment by cdobs** [comment]
Integrated corrections that were noted by R. Travis for the first review of CTDGVM. Awaiting final review from P. Brickley.

**Comment by pbrickley** [comment]
Still cannot locate 09236.  I think this is a typo.

**Comment by pbrickley** [comment]
Found 09236.  This was delivered on gs_524. We have the original cal sheet. 
OpenOcean_524_Factory._Config_Calibration_2015-03-24

Glider failed QCT on delivery and was sent back to TWR for correction. TWR subsequently flooded it and replaced the CTD. Replaced with 09283

**Comment by pbrickley** [comment]
CTD 09297 exists.  Delivered on glider 578. Cal sheet on Vault under 578 Config_Calibration PDF.  Cal date 4/24/2015, so I think this was just a typo in the date.

**Comment by pbrickley** [comment]
CGINS-CTDGVM-09065__20170517  This is a typo. Cal date was 5/2/2017. Cal doc on Vault under OpenOceanGliders 363.  The scan is named GL363.pdf.

**Comment by pbrickley** [comment]
Updates and notes for CTDGV noted on google sheet.

**Comment by cdobs** [comment]
Addressing PB comments:
-Good find on 09236: Due to the fact that it would need to be added to sensor bulkload and also that it was never deployed on a glider, I recommend that we keep this one out of the pull request entirely (which it it currently is).
-09297 duplicate entry in the tracking spreadsheet crossed out. Turns out that a typo in a cal date led us to believe there was a second calibration of this instrument, when there wasn't. 
-09065 typo corrected. Updated name of calibration csv and calibration date within file.

**Comment by cdobs** [comment]
First review of PCO2W-B and PCO2W-C complete. No file changes needed. 
Second review of PCO2W-B and PCO2W-C still pending.

**Comment by cdobs** [comment]
First review of PHSEN-D, PHSEN-E and PHSEN-F completed by Andrew Reed. No recommended changes.

**Comment by cdobs** [comment]
Second review of PHSEN-D, PHSEN-E and PHSEN-F completed by Collin Dobson. Only recommended change is that the calibration file on Vault for SN P0087 (cal date 2/3/16) needs to be renamed with correct date. No changes to calibration csvs needed.

Only remaining review needed is the second review of PCO2W-B and PCO2W-C.

**Pull request merged**
