### PR TITLE
Corrected endurance 7 recovery and deployment times

### PR DESCRIPTION
**Pull request by najascutellatus**
It appears there were some dummy dates entered in the deployment
sheets. I went ahead and corrected them all

### CODE REVIEW

**Comment by danmergens** [comment]
Looks like you may have unintentionally removed deployment 6 by changing
the dates for CE09OSPM

**Comment by najascutellatus** [comment]
@danmergens Deployment 6 is still there according to https://github.com/ooi-integration/asset-management/blob/master/deployment/CE09OSPM_Deploy.csv

**Comment by friedrichknuth** [comment]
The end dates for deployment 6 appear to be after the start dates for deployment 7. Is that correct?

**Comment by friedrichknuth** [comment]
From Mike: This is correct. D7 went in before D6 came out.

**Comment by najascutellatus** [comment]
Source: [SKQ201704S_daily_2017-04-12.pdf](https://github.com/ooi-integration/asset-management/files/1005962/SKQ201704S_daily_2017-04-12.pdf)

**Comment by cwingard** [comment]
We will deploy the new instance of a mooring before recovering the older 
instance more often than not. This way we can get cross-comparisons 
between the sensors and shipboard sampling. Also, we have to clear the 
deck of the new mooring instance(s) before we can recover the old one(s).

**Comment by danmergens** [comment]
yes - sorry for my confusion - because all the other updates were to the deployment start times, I mixed up the stop time addition as a change to the deployment start time for deployment 6. All good now.

**Pull request merged**
