### PR TITLE
Added calibration file for FLNTUA SN: 3398

### PR DESCRIPTION
**Pull request by funnyabc**

### CODE REVIEW

**Comment by friedrichknuth** [comment]
The travis check states 

`root: ERROR: Found duplicate keys in bulk load: Counter({'ATOSU-70110-00007': 1})`

I saw that FLNTURD SN: 3398 already existed in sensor_bulk_load-AssetRecord.csv under a placeholder UID, so I first renamed it

https://github.com/ooi-integration/asset-management/commit/7f3bb762b639b466bf418153d007b6931f7d00c3

but then saw funnyabc was adding it back with proper info in the pending pull request, so I removed the dummy entry all together. 

https://github.com/ooi-integration/asset-management/commit/454b23e966e2080ee12b4b24e69bc75d99339bcf

Travis still kicks the error. The only other place I found ATOSU-70110-00007, is in the unclassified bulkload sheet.

https://github.com/ooi-integration/asset-management/search?utf8=%E2%9C%93&q=ATOSU-70110-00007&type=

My next step would be to remove ATOSU-70110-00007 from there.

**Comment by friedrichknuth** [comment]
Removed ATOSU-70110-00007 from unclassified bulkload sheet.

https://github.com/ooi-integration/asset-management/commit/1848abc745e0199af8e72533b5a9d4db5956f6e1

Travis is still failing with the same error.

**Comment by friedrichknuth** [comment]
Maybe Travis isn't checking the content of this pull request against the latest info in the repo following my commits, which came after the pull request was submitted? In that case, we would probably need to close this pull request out and resubmit it.

**Comment by funnyabc** [comment]
Closing pull request and resubmitting, per Friedrich's suggestion.

**Pull request closed without merging**
