### PR TITLE
Updates for Pioneer 10b cruise

### PR DESCRIPTION
**Pull request by rtravis-whoi**
Updated Pioneer glider deploy sheets - GL336, GL376, GL389
Updated sensor bulk load for glider sensors
Added glider sensor cal files

### CODE REVIEW

**Comment by lgarzio** [comment]
@danmergens what do these errors mean?

**Comment by rtravis-whoi** [comment]
I checked to see if that earlier issue with the cruise ID (thread between Stuart & Dan re pull request #548) had been closed out and it looked like it had, so I thought it would be safe to go ahead with this...but maybe there's still something hung up w that & caused these errors?  Let me know if I need to close this pull request.

**Comment by danmergens** [comment]
Here's what I see from Travis (I re-triggered the build just to make sure it wasn't an anomaly):

```
  File "/home/travis/build/ooi-integration/asset-management/test/unit/test_cal.py", line 58, in check_filename
    uid, timestamp = self.parse_cal_filename(filename)
ValueError: need more than 1 value to unpack
```

This means that `parse_cal_filename` is returning less than the expected two values (`uid` and `timestamp` are expected). It's possible that there is an error parsing the calibration file, causing it to return prematurely, or someone changed `parse_cal_filename`.

**Comment by rtravis-whoi** [comment]
Thanks Dan & Russ.  Poor eyesight on my part!  I'll have someone here show me how to run a nosetest.

**Comment by lgarzio** [comment]
This pull request will have conflicts with the cruise sheet because of the previous merged pull request

**Comment by lgarzio** [comment]
@danmergens can you review this? I believe there will be conflicts with the cruise sheet and I'm not sure why github isn't catching that. The only thing I can think of is your request for changes is preventing the check?

**Comment by rtravis-whoi** [comment]
I need to add AUV deploy info and add to the sensor bulk load sheet.  Would it be easiest for me to close this pull request and start over?

**Comment by danmergens** [comment]
@leilabbb You can see on the Conversation tab that all checks have passed, so the TravisCI tests have been retriggered and passed. If there is something we should be checking for and missed, then it should be added to the unit tests. If there is something specific that you know is wrong on this pull request, you should request changes in your review to prevent the merge until it has been fixed. 

@rtravis-whoi You can add your additional updates to this pull request.

**Pull request merged**
