### PR TITLE
Endurance 5 Calfile Fixes

### PR DESCRIPTION
**Pull request by desiderr**
No calibration coefficients changed.
Only file actions: renaming Omaha-derived calfiles with vendor calibration date.

### CODE REVIEW

**Comment by desiderr** [comment]
All calibration coefficients and file changes checked by R Desiderio and H. Rappleyea.

**Comment by danmergens** [comment]
Not sure what "Omaha-derived" calfile means. The filename includes the calibration timestamp which is used during ingestion of the calibration files during an asset management update as the effective time.

**Comment by desiderr** [comment]
Before the current asset management system was implemented in 2017, calibration coefficients were entered into asset management by uploading one excel file per surface mooring deployment (one example was Omaha_Cal_Info_CE01ISSM_00005.xlsx). These calfiles contained no instrument calibration dates but did contain the respective surface mooring deployment dates. When the calibration coefficients in these 'Omaha' files were extracted and converted into the current csv calfile format the surface mooring deployment dates were written into the calibration filenames to serve as effective calibration timestamps. Some time afterwards the MIOs decided that replacing these deployment dates with instrument calibration dates would be preferable.

**Comment by danmergens** [comment]
Ah, yes. Pete Cable pulled apart the "Omaha_Cal_Info_*" files into the calibration and deployment information, I was part of that design process. We decided it would be better to have the calibration specific to the instrument, rather than deployment, based on input from the MIOs. I think we are now finally catching up to that design point by updating the calibration input files accordingly.

**Pull request merged**
