### PR TITLE
Master

### PR DESCRIPTION
**Pull request by leilabbb**

### CODE REVIEW

**Comment by desiderr** [comment]
Leila - 

At first glance, it looks as if you're changing everything in the file - is that because you re-ordered the columns? Are you just changing bottom depths?

- Russ



----- Original Message -----

**Comment by leilabbb** [comment]
Yes, It is my script reordering the columns, but I tried to keep the deployment numbers as the first column.

And yes I am checking few things:
- if all reference designators are in for every deployment  to keep consistency in the system.
- are the depth columns complete, which I am missing the water depth for CE02SHSP.

I have also noticed that deployment 2 has a different Node SP002 and all the other deployments the node is SP001. Is that correct?

Thanks,

**Comment by desiderr** [comment]
I think you misread the columns - the nodes are not all 001 except for deployment 00002. The nodes switch between deployments, according to the serial number of the cspp; I see instances of 003 and 006 in the CE02SHSP_Deploy.csv file on GitHub. 

To check the profiler serial number, you need to look at the config.xlsx file for that deployment. Attached is the config.xlsx file for the 2nd deployment of CE02SHSP; you should be able to locate this file on alfresco.

If you check out the entry for profiler serial number on row 32, you will see "002". 

The node for deployment 2 is therefore 002, not 001.

Have you or anyone else been changing node.uids and sensor.uids for the Endurance cspp deploy files?


----- Original Message -----

**Comment by leilabbb** [comment]
No, I do not believe anyone has been changing node or sensor UIDs.

I was not talking about the node column I am referring to the reference designator column:

Deployment 2 reference designator names vs the other deployments: Is this correct or is it a typo?
e.g. 
CE02SHSP-SP002-01-DOSTAJ000   vs CE02SHSP-SP001-01-DOSTAJ000
CE02SHSP-SP002-04-OPTAAJ000   vs CE02SHSP-SP001-04-OPTAAJ000
CE02SHSP-SP002-02-VELPTJ000    vs CE02SHSP-SP001-02-VELPTJ000
CE02SHSP-SP002-05-NUTNRJ000  vs CE02SHSP-SP001-05-NUTNRJ000
CE02SHSP-SP002-06-SPKIRJ000    vs CE02SHSP-SP001-06-SPKIRJ000

etc

Thanks.

**Comment by desiderr** [comment]
I don't know for sure, but I strongly suspect it's a typo because I checked all the other reference designators for the other Endurance cspps deployed at ce01, ce06, and ce07, and all of them use SP001 for all deployments.

----- Original Message -----

**Comment by danmergens** [comment]
Let's make sure the reference designators are correct. I believe there was one case where there was a second mooring deployed at the same location for a time (SP002).

**Comment by leilabbb** [comment]
Just doubled checked the lists I know of and it is not listed in the 1100 document or the data team database.

**Comment by desiderr** [comment]
Good catch, Dan, I had forgotten all about that. 

The deployment and recovery dates for deployments 00001 and 00002 overlap almost exactly; that was when Jon deployed two different cspps at ce02 concurrently. I believe one of the CI fixes was to change the 00002 reference designator.

----- Original Message -----

**Comment by leilabbb** [comment]
ok, will leave it as is and will work on adding it to the system documents.

**Pull request merged**
