### PR TITLE
Ce glider

### PR DESCRIPTION
**Pull request by s-pearce**
For CE gliders adds:
deployments: 311-00007 and 384-0000
cruises: ML20190417 and OC1905C
recoveries: 327-00008, 319-00008, 383-00008, 382-00005
calibrations for the instruments

### CODE REVIEW

**Comment by s-pearce** [comment]
@danmergens Ready for release tag creation and pushed to production
@cwingard for reference

**Comment by cwingard** [comment]
Cruise ID for 11A is SKQ201910S not SKQ201905S as you have it.

**Comment by cwingard** [comment]
Add calibration/DOSTAM/CGINS-DOSTAM-00404__20181022.csv. After that, the Travis build should pass. @danmergens wait to tag and release as we have additional updates coming in the next 2-3 days for the second half of our cruise. I'd like to get all of these updates also pushed to production.

**Comment by s-pearce** [comment]
@cwingard the cruise ID SKQ201905S was a vessel of opportunity recovery for a glider, not the same cruise.  I forgot to add it to the cruise ID file.  It is added now along with DOSTAM SN0404 to sensor bulk load.
Stuart

**Comment by s-pearce** [comment]
> 

> @danmergens wait to tag and release as we have additional updates coming in the next 2-3 days for the second half of our cruise. I'd like to get all of these updates also pushed to production.

@danmergens despite waiting on the release tag, can you still go ahead and merge my changes, there are some others that are waiting on this merge to go through.  Thanks, -Stuart

**Pull request merged**
