### PR TITLE
Refactored Asset Management

### PR DESCRIPTION
**Pull request by r-swilderd**

### CODE REVIEW

**Comment by r-swilderd** [comment]
Refactored Asswt Managment for Review

**Comment by petercable** [comment]
I would recommend we bundle these directories into a single folder until we remove or archive the existing sheets. Bob had suggested "refactored_asset_management" previously.

**Comment by r-swilderd** [comment]
Updated

**Comment by janeen666** [comment]
Pull request from from  S. Wilderdyke branch.  Ticket 11004.

**Pull request merged**
