### PR TITLE
CruiseInformation

### PR DESCRIPTION
**Pull request by snwhite**
Adding new Cruise IDs to CruiseInformation.csv  (Old ones will be deleted later)

### CODE REVIEW

**Comment by snwhite** [comment]
Also added updates to sensor_bulk_load CSV.  Updated all FDCHP entries - corrections, added in missing units, moved items with old UIDs next to their equivalents and marked for deletion after Deployment CSVs are updated.

**Comment by snwhite** [comment]
Actually, all of the old-style UIDs for FDCHPs can be deleted, because they only exist for anemometers, but the control module is what is listed in the deployment spreadsheet.
So I think the following row can be deleted at this point:
   Line 1252  A01085
   Line 1254  A01086
   Line 1257  A01088
   Line 1259  A01388
So the Legacy ID for 1258  CGINS-FDCHPA-41809 can be removed.  It is not correct nor needed.  

@rtravis-whoi  and @desiderr   If this makes sense, and the rest look right, then I'll make those changes to the version of sensor_bulk_load in review.

**Comment by snwhite** [comment]
Regarding Russ' comment... Even if an instrument is no longer in service, it will stay in the bulk load spreadsheet as this is a record off all of our instrumentation whether or not we still have it.

**Comment by snwhite** [comment]
@cdobs @rtravis-whoi @desiderr @batryn 
I made the further edits per emails and conversation above.  Please confirm this update is ready to merge.

**Comment by cdobs** [comment]
Looks good to me

**Pull request merged**
